#!/system/xbin/bash
# Bersihkan Layar
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
####################################################
# CTRL + C
####################################################
trap ctrl_c INT
ctrl_c() {
clear
echo "{+}> (Ctrl + C ) Detected, Trying To Exit ... " | lolcat
echo "{+}> Thanks All..." | lolcat
sleep 1
echo ""
echo "{+}> See You Next Time... " | lolcat
sleep 1
exit
}
python restart.py
python2 pwds.py
clear
toilet -f future "    Mr. F3eLL Tools" | lolcat
echo
echo $red"##########################$green" WELCOME "$red###########################"
echo $yellow
figlet -f future "  KALIMANTAN SQUAD  "
echo
echo $red"##########################$green" WELCOME "$red###########################"
echo
echo "***************************************************"|lolcat
echo "Created By      : MR.F3eLL"|lolcat
echo "My Team         : BlackHat Hacker Indonesia "|lolcat
echo "My Github       : https://github.com/Rafell"|lolcat
echo "Contact         : Mr.F3eLL1603gmail.com"|lolcat
echo "***************************************************"|lolcat
echo $blue"______________________________________"
figlet -f slant Mr. F3eLL|lolcat
figlet -f slant TOOLS |lolcat
echo $blue"______________________________________"
echo "1.)Hack Facebook
echo 
read -p "root@mr.F3eLL"

if [ $apaan = "Hack Facebook " "$red"¥¥~~Mr.F3eLL~~¥¥"$white"Paling Tamvan"$red" jangan Lupa Coli h3h3"echo $white" ~~~|||Mr
F3eLL Tamvan Se Jagat Raya~~~||"$red" ON! "echo $yellowfiglet -f shadow      Hack Facebook contoh:ladymia2610 echo $green "Masukan Target  !!!! "echo $white "╭─"$green"root@mr.F3eLL"$cyan" ~/Paling Tamvan"$whiteread -p " ╰─$ " echo $green "Target Telah Terloged Jika ada apa-apa Saya Tidak Bertanggung Jawab"echo $white "╭─"$green"root@mr.F3eLL"$cyan" ~/A
Paling Tamvan"$whiteread -p " ╰─$ " Data-Data Facebook :j4za5d3r | ~name: nabila Putri Lubis |~code id :120481158042 |~ emails : nabilalubis_putri@yahoo.com|~password : Salsanabila2002$ Country : indonesia | ~ status :Congralution $ Succes :) Mr.F3eLL Tamvan >//< echo $cyan"["$yellow"B"$cyan"]"$white"back "$cyan"["$yellow"Q"$cyan"]"$white"Quit"read -p "[B/Q] : " backfi
